//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessonScheduler.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stages
    {
        public int Id { get; set; }
        public Nullable<int> StageNumber { get; set; }
        public Nullable<decimal> TimeDuration { get; set; }
        public string Material { get; set; }
        public string TeacherActivity { get; set; }
        public string StudentActivity { get; set; }
        public Nullable<int> IdPlan { get; set; }
    
        public virtual Plans Plans { get; set; }
    }
}
